version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk
    working_directory: ~/esjwt-realm
    environment:
      GRADLE_OPTS: -Xmx3200m
      artifact_dir: "artifacts"

    steps:
      - checkout
      - run:
          name: Setup Build Variables
          command: |
            echo 'export COMMIT_MESSAGE="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: ./gradlew clean buildZip
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Gradle Check
          command: ./gradlew check

      - run:
          name: Collect Test Artifacts
          command: |
            mkdir -p ${artifact_dir}/reports/ ${artifact_dir}/output/
            cp -r build/reports ${artifact_dir}/reports/
          when: always
      - store_artifacts:
          path: tmp/artifacts
